import { Inter } from "next/font/google"
// import "./globals.css";
import NavBar from "@/components/NavBar"
import { ThemeProvider } from "@/contexts/ThemeContext"
import ThemeToggleButton from "@/components/ThemeToggleButton"
import '@/styles/global.css'
import CounterProvider from '@/store/CounterProvider'
import CounterDisplay from '@/features/counter/CounterDisplay'

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <CounterProvider>
      <ThemeProvider>
        <body>
          <header>
          <ThemeToggleButton />
          <CounterDisplay />
            <NavBar />
          </header>
          {children}
        </body>
      </ThemeProvider>
      </CounterProvider>
    </html>
  )
}
